### ISSUE TITLE
Fix add vcs cred documentation

### ISSUE THREAD

**Issue by eccramer** [level11consulting/ocelot#163]
When adding VCS creds, the documentation lists the yml file field for the credfile as:

```
vcs:
  - clientId: <client id from bitbucket consumer>
    clientSecret: <client secret from bitbucket consumer>
    tokenURL: https://bitbucket.org/site/oauth2/access_token
    acctName: <account name in bitbucket> 
    type: bitbucket
```

However, since that was written, apparently the field has changed name to `subType`:

```
vcs:
  - clientId: <redacted>
    clientSecret: <redacted>
    tokenURL: https://bitbucket.org/site/oauth2/access_token
    acctName: eccramer
    subType: bitbucket
```

Without the subType field in the yml, ocelot CLI dies with an obscure error:

```
eccramer-mbp:ecramer-ocelot-test evancramer$ ocelot creds vcs add --credfile-loc ~/ocelotconfigs/ecramer-test-ocy.yml
Could not add credentials for account: eccramer
Error: rpc error: code = InvalidArgument desc = Subtype must be of vcs type: BITBUCKET | GITHUB
```

We need to update the documentation for this and change the `type` field to `subType`.
